dist: bionic
language: ruby
rvm: 2.6
services:
  - postgresql
  - mysql
addons:
  postgresql: 10
env:
  - ADAPTER=postgresql
  - ADAPTER=mysql2
script: bundle exec rake test
before_install:
  - mysqladmin create hypershield_test
  - createdb hypershield_test
notifications:
  email:
    on_success: never
    on_failure: change
